import QtQuick

QtObject {
  property string localeName: String(Qt.locale().name || 'en').toLowerCase()
  readonly property bool spanish: localeName.indexOf('es') === 0

  function choose(es, en) {
    return spanish ? es : en
  }

  function text(key) {
    switch (String(key || '')) {
    case 'welcome_title': return choose('Bienvenido a Proton VPN', 'Welcome to Proton VPN')
    case 'welcome_description': return choose('Configura cómo se integra con Omarchy. Puedes cambiarlo después.', 'Choose how it integrates with Omarchy. You can change this later.')
    case 'language': return choose('Idioma', 'Language')
    case 'start_with_omarchy': return choose('Iniciar con Omarchy', 'Start with Omarchy')
    case 'start_with_omarchy_description': return choose('Mantiene listo el estado compartido de la VPN.', 'Keeps shared VPN state ready.')
    case 'auto_connect': return choose('Conectar automáticamente', 'Connect automatically')
    case 'auto_connect_description': return choose('Usa la conexión predeterminada al iniciar.', 'Uses the default connection at startup.')
    case 'migration_found': return choose('Se encontró información local del cliente anterior y se migrará sin borrar el original.', 'Local data from the earlier client was found and will be migrated without deleting the original.')
    case 'continue': return choose('Continuar', 'Continue')
    case 'store_unavailable': return choose('El almacén local todavía no está disponible.', 'The local store is not available yet.')
    case 'locations': return choose('Ubicaciones', 'Locations')
    case 'countries': return choose('Países', 'Countries')
    case 'gateways': return choose('Gateways', 'Gateways')
    case 'servers': return choose('Servidores', 'Servers')
    case 'search_locations': return choose('Buscar país, ciudad o servidor', 'Search country, city or server')
    case 'fastest_server': return choose('Servidor más rápido', 'Fastest server')
    case 'fastest_gateway': return choose('Gateway más rápido', 'Fastest gateway')
    case 'standard': return choose('Estándar', 'Standard')
    case 'fastest_secure_core': return choose('Secure Core más rápido', 'Fastest Secure Core')
    case 'fastest_p2p': return choose('Servidor P2P más rápido', 'Fastest P2P server')
    case 'fastest_tor': return choose('Servidor Tor más rápido', 'Fastest Tor server')
    case 'connect_best_available': return choose('Conectar a la mejor opción disponible', 'Connect to the best available option')
    case 'best_available_profile_target': return choose('Usar siempre la mejor opción disponible', 'Always use the best available option')
    case 'no_servers_found': return choose('No se encontraron servidores.', 'No servers found.')
    case 'loading_servers': return choose('Cargando servidores…', 'Loading servers…')
    case 'profiles': return choose('Perfiles', 'Profiles')
    case 'edit_profile': return choose('Editar perfil', 'Edit profile')
    case 'profile_name': return choose('Nombre del perfil', 'Profile name')
    case 'profile_icon': return choose('Ícono y color', 'Icon and color')
    case 'open_website': return choose('Abrir un sitio web', 'Open a website')
    case 'open_application': return choose('Abrir una aplicación', 'Open an application')
    case 'private_browsing': return choose('Navegación privada', 'Private browsing')
    case 'private_browsing_description': return choose('Abrir en una ventana privada', 'Open in a private window')
    case 'application': return choose('Aplicación', 'Application')
    case 'select_application': return choose('Selecciona una aplicación', 'Select an application')
    case 'profile_target': return choose('Destino', 'Target')
    case 'choose_location': return choose('Elegir ubicación', 'Choose location')
    case 'country_code': return choose('Código de país', 'Country code')
    case 'server_name': return choose('Nombre del servidor', 'Server name')
    case 'gateway_name': return choose('Nombre del gateway', 'Gateway name')
    case 'protocol': return choose('Protocolo', 'Protocol')
    case 'enabled': return choose('Activado', 'Enabled')
    case 'disabled': return choose('Desactivado', 'Disabled')
    case 'netshield_level': return choose('Nivel de NetShield', 'NetShield level')
    case 'netshield_level_0': return choose('Sin bloqueo', 'No blocking')
    case 'netshield_level_1': return choose('Bloquear malware', 'Block malware')
    case 'netshield_level_2': return choose('Malware, anuncios y rastreadores', 'Malware, ads and trackers')
    case 'moderate_nat': return choose('NAT moderado', 'Moderate NAT')
    case 'alternative_routing': return choose('Enrutamiento alternativo', 'Alternative routing')
    case 'alternative_routing_description': return choose('Ayuda a alcanzar Proton cuando la API está bloqueada', 'Helps reach Proton when the API is blocked')
    case 'ipv6': return 'IPv6'
    case 'ipv6_description': return choose('Usar IPv6 cuando el servidor lo admita', 'Use IPv6 when the server supports it')
    case 'ipv6_leak_protection': return choose('Protección contra fugas IPv6', 'IPv6 leak protection')
    case 'ipv6_leak_protection_description': return choose('Bloquea IPv6 fuera del túnel', 'Blocks IPv6 outside the tunnel')
    case 'local_area_network_access': return choose('Acceso a la red local', 'Local network access')
    case 'local_area_network_access_description': return choose('Permite dispositivos en redes privadas y link-local fuera del túnel', 'Allows private and link-local network devices outside the tunnel')
    case 'local_dns_access': return choose('Acceso al DNS local', 'Local DNS access')
    case 'local_dns_access_description': return choose('Permite consultar directamente los resolvers de tu red física', 'Allows direct queries to resolvers on your physical network')
    case 'notifications': return choose('Notificaciones', 'Notifications')
    case 'notifications_description': return choose('Estados, errores y solicitudes de autenticación', 'Status, errors and authentication prompts')
    case 'port_forwarding_notifications': return choose('Notificaciones del puerto', 'Port forwarding notifications')
    case 'port_forwarding_notifications_description': return choose('Avisar cuando Proton asigne un puerto', 'Notify when Proton assigns a port')
    case 'netshield_statistics': return choose('Bloqueado por NetShield', 'Blocked by NetShield')
    case 'malware': return 'Malware'
    case 'ads': return choose('Anuncios', 'Ads')
    case 'trackers': return choose('Rastreadores', 'Trackers')
    case 'port_forwarding': return choose('Reenvío de puertos', 'Port forwarding')
    case 'save_profile': return choose('Guardar perfil', 'Save profile')
    case 'delete_profile': return choose('Eliminar perfil', 'Delete profile')
    case 'delete_profile_confirm': return choose('¿Eliminar este perfil y sus recientes asociados?', 'Delete this profile and its associated recents?')
    case 'delete': return choose('Eliminar', 'Delete')
    case 'no_profiles': return choose('Todavía no hay perfiles. Crea uno con +.', 'No profiles yet. Create one with +.')
    case 'recents': return choose('Recientes', 'Recents')
    case 'recents_and_favorites': return choose('Recientes y favoritos', 'Recents & favorites')
    case 'recents_description': return choose('Reutiliza o fija conexiones anteriores', 'Reuse or pin previous connections')
    case 'favorites_description': return choose('Las estrellas fijan conexiones sin duplicar el historial.', 'Stars pin connections without duplicating history.')
    case 'saved_connection': return choose('Conexión guardada', 'Saved connection')
    case 'saved_connections': return choose('Conexiones guardadas', 'Saved connections')
    case 'no_recents': return choose('Tus conexiones recientes aparecerán aquí.', 'Your recent connections will appear here.')
    case 'use_as_default': return choose('Usar como conexión predeterminada', 'Use as default connection')
    case 'default_connection_active': return choose('Conexión predeterminada actual', 'Current default connection')
    case 'delete_recent': return choose('Eliminar del historial', 'Delete from history')
    case 'confirm_delete_recent': return choose('Confirmar eliminación', 'Confirm deletion')
    case 'default_connection': return choose('Conexión predeterminada', 'Default connection')
    case 'default_connection_description': return choose('Quick Connect y el autoarranque resuelven esta selección desde el agente compartido.', 'Quick Connect and autostart resolve this selection through the shared agent.')
    case 'random_server': return choose('Servidor aleatorio', 'Random server')
    case 'last_connection': return choose('Última conexión', 'Last connection')
    case 'default_fastest': return choose('Más rápido', 'Fastest')
    case 'default_random': return choose('Aleatorio', 'Random')
    case 'default_last': return choose('Última conexión', 'Last connection')
    case 'default_recent': return choose('Reciente seleccionado', 'Selected recent')
    case 'default_profile': return choose('Perfil seleccionado', 'Selected profile')
    case 'default_used_by_quick_connect': return choose('Aunque el auto-connect esté apagado, Quick Connect usa esta selección.', 'Even with auto-connect off, Quick Connect uses this selection.')
    case 'target_fastest': return choose('Más rápido', 'Fastest')
    case 'target_country': return choose('País', 'Country')
    case 'target_server': return choose('Servidor', 'Server')
    case 'target_secureCore': return 'Secure Core'
    case 'target_p2p': return 'P2P'
    case 'target_tor': return 'Tor'
    case 'target_gateway': return 'Gateway'
    case 'target_gatewayServer': return choose('Servidor de gateway', 'Gateway server')
    case 'make_default_profile': return choose('Usar al conectar automáticamente', 'Use for automatic connection')
    case 'default_profile_active': return choose('Conexión predeterminada', 'Default connection')
    case 'settings': return choose('Ajustes', 'Settings')
    case 'connection': return choose('Conexión', 'Connection')
    case 'protection': return choose('Protección', 'Protection')
    case 'account': return choose('Cuenta', 'Account')
    case 'plan_unknown': return choose('Plan no disponible', 'Plan unavailable')
    case 'plan_free': return 'Proton Free'
    case 'plan_paid': return choose('Plan Proton VPN de pago', 'Paid Proton VPN plan')
    case 'shared_session_description': return choose('La sesión pertenece al agente y se comparte con el plugin y el cliente independiente.', 'The agent owns this session and shares it with the plugin and standalone client.')
    case 'manage_account': return choose('Administrar cuenta', 'Manage account')
    case 'manage_subscription': return choose('Administrar suscripción', 'Manage subscription')
    case 'upgrade_plan': return choose('Mejorar plan', 'Upgrade plan')
    case 'opens_secure_browser': return choose('Se abre en tu navegador predeterminado', 'Opens in your default browser')
    case 'authenticated_browser_handoff': return choose('Proton prepara un handoff autenticado cuando está disponible', 'Proton prepares an authenticated handoff when available')
    case 'account_web_boundary': return choose('Proton gestiona pagos y datos de cuenta en su sitio web; no se incrustan páginas web en el plugin.', 'Proton manages billing and account data on its website; the plugin never embeds web pages.')
    case 'connecting_to': return choose('Conectando a', 'Connecting to')
    case 'vpn_disconnected': return choose('La VPN está desconectada', 'VPN is disconnected')
    case 'disconnect_proton_vpn': return choose('Desconectar Proton VPN', 'Disconnect Proton VPN')
    case 'quick_connect': return choose('Quick Connect', 'Quick Connect')
    case 'secure_core_active': return choose('La conexión actual usa Secure Core', 'Current connection uses Secure Core')
    case 'secure_core_description': return choose('Conecta mediante un servidor de entrada reforzado', 'Connect through a hardened entry server')
    case 'kill_switch_advanced_description': return choose('Avanzado · protección siempre activa', 'Advanced · always-on protection')
    case 'kill_switch_standard_description': return choose('Protección estándar activada', 'Standard protection enabled')
    case 'kill_switch_description': return choose('Protege el tráfico si se cae la VPN', 'Protect traffic if the VPN drops')
    case 'netshield_full_description': return choose('Bloqueando malware, anuncios y rastreadores', 'Blocking malware, ads and trackers')
    case 'netshield_malware_description': return choose('Bloqueando malware', 'Blocking malware')
    case 'netshield_off_description': return choose('La protección DNS está apagada', 'DNS-level protection is off')
    case 'apps': return choose('aplicaciones', 'apps')
    case 'split_tunneling_off_description': return choose('El túnel dividido por aplicación está apagado', 'App-based split tunneling is off')
    case 'application': return choose('Aplicación', 'Application')
    case 'kill_switch_off': return choose('Desactivado', 'Off')
    case 'kill_switch_standard': return choose('Estándar', 'Standard')
    case 'kill_switch_advanced': return choose('Avanzado · siempre activo', 'Advanced · always on')
    case 'active_port': return choose('Puerto activo', 'Active port')
    case 'custom_dns': return 'Custom DNS'
    case 'apply': return choose('Aplicar', 'Apply')
    case 'split_tunneling': return choose('Túnel dividido', 'Split tunneling')
    case 'excluded_locations': return choose('Ubicaciones excluidas', 'Excluded locations')
    case 'excluded_locations_short_description': return choose('Omitirlas al elegir automáticamente', 'Skip them during automatic selection')
    case 'excluded_locations_description': return choose('Los perfiles y ubicaciones elegidos explícitamente aún pueden usar estos lugares. Se aplican al servidor más rápido, aleatorio y otras selecciones automáticas.', 'Explicit profiles and locations can still use these places. Exclusions apply to fastest, random and other automatic selections.')
    case 'excluded': return choose('Excluidas', 'Excluded')
    case 'add_location': return choose('Agregar ubicación', 'Add location')
    case 'excluded_country': return choose('País', 'Country')
    case 'excluded_state': return choose('Estado o región', 'State or region')
    case 'excluded_city': return choose('Ciudad', 'City')
    case 'anonymous_crash_reports': return choose('Reportes anónimos de fallos', 'Anonymous crash reports')
    case 'anonymous_usage_statistics': return choose('Estadísticas de uso anónimas', 'Anonymous usage statistics')
    case 'anonymous_usage_statistics_description': return choose('Ayudan a superar bloqueos y mejorar el rendimiento', 'Helps overcome blocks and improve performance')
    case 'connection_feedback_question': return choose('¿Cómo funciona esta conexión?', 'How is this connection working?')
    case 'support': return choose('Soporte', 'Support')
    case 'diagnostics': return choose('Diagnósticos', 'Diagnostics')
    case 'diagnostics_short_description': return choose('Estado del core y fuentes de logs', 'Core status and log sources')
    case 'diagnostics_description': return choose('Comprueba qué componentes y fuentes acotadas están disponibles para un reporte.', 'Check which components and bounded sources are available for a report.')
    case 'agent_status': return choose('Estado del agente', 'Agent status')
    case 'available': return choose('Disponible', 'Available')
    case 'unavailable': return choose('No disponible', 'Unavailable')
    case 'canonical_store': return choose('Almacén canónico', 'Canonical store')
    case 'diagnostic_sources': return choose('Fuentes para reportes', 'Report sources')
    case 'diagnostic_agent': return choose('Agente y bridge de Proton', 'Proton agent and bridge')
    case 'diagnostic_network_manager': return 'NetworkManager'
    case 'diagnostic_split_tunneling': return choose('Servicio de túnel dividido', 'Split tunneling service')
    case 'diagnostic_unknown': return choose('Fuente desconocida', 'Unknown source')
    case 'diagnostic_sources_partial': return choose('Algunas fuentes no están disponibles', 'Some sources are unavailable')
    case 'diagnostics_privacy': return choose('El panel sólo recibe disponibilidad y tamaño. El contenido de los journals no cruza el IPC.', 'The panel receives only availability and size. Journal contents never cross IPC.')
    case 'checking_diagnostics': return choose('Comprobando…', 'Checking…')
    case 'refresh': return choose('Actualizar', 'Refresh')
    case 'about': return choose('Acerca de', 'About')
    case 'sign_out': return choose('Cerrar sesión', 'Sign out')
    case 'confirm_sign_out': return choose('Confirmar cierre de sesión', 'Confirm sign out')
    case 'sign_out_shared_warning': return choose('Esto desconectará la VPN y cerrará la sesión compartida en el plugin y el cliente independiente.', 'This disconnects the VPN and signs out the session shared by the plugin and standalone client.')
    case 'open': return choose('Abrir', 'Open')
    case 'home': return choose('Inicio', 'Home')
    case 'countries_and_servers': return choose('Países y servidores', 'Countries & servers')
    case 'browse_locations': return choose('Explorar ubicaciones y Gateways', 'Browse locations and Gateways')
    case 'saved_connection_presets': return choose('Conexiones guardadas', 'Saved connection presets')
    case 'connection_details': return choose('Detalles de conexión', 'Connection details')
    case 'connection_details_description': return choose('Servidor, protocolo y tráfico', 'Server, protocol and traffic')
    case 'connection_app_preferences': return choose('Preferencias de conexión y aplicación', 'Connection and app preferences')
    case 'official_core_note': return choose('La conexión y las protecciones usan el core oficial de Proton para Linux.', 'Connection and protection use the official Proton Linux core.')
    case 'not_connected': return choose('Sin conexión VPN', 'Not connected')
    case 'public_connection_details': return choose('Información de tu conexión pública actual', 'Your current public connection information')
    case 'network': return choose('Red', 'Network')
    case 'ip_address': return choose('Dirección IP', 'IP address')
    case 'provider': return choose('Proveedor', 'Provider')
    case 'traffic': return choose('Tráfico', 'Traffic')
    case 'download': return choose('Descarga', 'Download')
    case 'upload': return choose('Subida', 'Upload')
    case 'exclude_mode': return choose('Excluir', 'Exclude')
    case 'include_mode': return choose('Incluir sólo', 'Include only')
    case 'exclude_mode_description': return choose('Las apps elegidas evitan la VPN.', 'Selected apps bypass the VPN.')
    case 'include_mode_description': return choose('Sólo las apps elegidas usan la VPN.', 'Only selected apps use the VPN.')
    case 'search_apps': return choose('Buscar aplicaciones', 'Search applications')
    case 'manual_executable': return choose('Ejecutable o ID de Flatpak', 'Executable or Flatpak ID')
    case 'split_requires_app': return choose('Selecciona al menos una aplicación o rango IP para activar este modo.', 'Select at least one application or IP range to enable this mode.')
    case 'split_kill_switch_conflict': return choose('Desactiva Kill Switch antes de activar el túnel dividido.', 'Turn off Kill Switch before enabling split tunneling.')
    case 'ip_ranges': return choose('Direcciones IP', 'IP addresses')
    case 'ip_range_placeholder': return choose('Dirección o CIDR, p. ej. 192.168.1.0/24', 'Address or CIDR, e.g. 192.168.1.0/24')
    case 'add_ip_range': return choose('Agregar rango IP', 'Add IP range')
    case 'remove_ip_range': return choose('Quitar rango', 'Remove range')
    case 'split_ip_ranges_requires_update': return choose('Actualiza Proton VPN for Omarchy para usar reglas por dirección IP.', 'Update Proton VPN for Omarchy to use IP address rules.')
    case 'support_center': return choose('Centro de soporte', 'Support center')
    case 'support_center_description': return choose('Guías oficiales de Proton VPN', 'Official Proton VPN guides')
    case 'report_issue': return choose('Reportar un problema', 'Report an issue')
    case 'categories': return choose('Categorías', 'Categories')
    case 'email': return choose('Correo electrónico', 'Email')
    case 'include_logs': return choose('Incluir diagnósticos', 'Include diagnostics')
    case 'include_logs_description': return choose('Adjunta logs recientes del agente y de red.', 'Attach recent agent and network logs.')
    case 'send_report': return choose('Enviar reporte', 'Send report')
    case 'report_sent': return choose('El reporte se envió correctamente.', 'The report was sent successfully.')
    case 'loading_support': return choose('Cargando categorías de soporte…', 'Loading support categories…')
    case 'about_description': return choose('Cliente nativo para Omarchy Quattro.', 'Native client for Omarchy Quattro.')
    case 'version': return choose('Versión', 'Version')
    case 'proton_linux_core': return choose('Core de Proton para Linux', 'Proton Linux core')
    case 'not_reported': return choose('No reportada', 'Not reported')
    case 'license': return choose('Licencia', 'License')
    case 'source_code': return choose('Código fuente', 'Source code')
    case 'privacy_policy': return choose('Política de privacidad', 'Privacy policy')
    case 'about_core_authority': return choose('Proton mantiene el core y la mecánica VPN; este frontend integra esa autoridad con Omarchy.', 'Proton maintains the core and VPN mechanics; this frontend integrates that authority with Omarchy.')
    case 'sign_in_title': return choose('Inicia sesión en Proton VPN', 'Sign in to Proton VPN')
    case 'sign_in_description': return choose('Usa tu cuenta de Proton para conectarte.', 'Use your Proton account to connect.')
    case 'advanced_kill_switch_blocked': return choose('Kill Switch avanzado está bloqueando la red mientras la VPN está desconectada.', 'Advanced Kill Switch is blocking the network while VPN is disconnected.')
    case 'disable_advanced_kill_switch': return choose('Desactivar Kill Switch avanzado', 'Disable Advanced Kill Switch')
    case 'username': return choose('Correo o nombre de usuario', 'Email or username')
    case 'password': return choose('Contraseña', 'Password')
    case 'sign_in': return choose('Iniciar sesión', 'Sign in')
    case 'two_factor_title': return choose('Verificación en dos pasos', 'Two-factor authentication')
    case 'two_factor_description': return choose('Ingresa el código de tu app autenticadora.', 'Enter the code from your authenticator app.')
    case 'two_factor_code': return choose('Código de 6 dígitos', '6-digit code')
    case 'authenticate': return choose('Verificar', 'Authenticate')
    case 'use_security_key': return choose('Usar llave de seguridad', 'Use security key')
    case 'use_authenticator': return choose('Usar app autenticadora', 'Use authenticator app')
    case 'security_key_title': return choose('Llave de seguridad', 'Security key')
    case 'security_key_description': return choose('Inserta o acerca tu llave y sigue las indicaciones.', 'Insert or tap your key and follow the prompts.')
    case 'security_key_pin': return choose('PIN de la llave', 'Security key PIN')
    case 'submit_pin': return choose('Enviar PIN', 'Submit PIN')
    case 'cancel': return choose('Cancelar', 'Cancel')
    case 'agent_reconnecting': return choose('Iniciando o reconectando con el agente…', 'Starting or reconnecting to the agent…')
    case 'agent_unavailable': return choose('El agente de Proton VPN no está disponible.', 'The Proton VPN agent is unavailable.')
    case 'backend_unavailable': return choose('El backend oficial de Proton no está disponible.', 'The official Proton backend is unavailable.')
    case 'retryable_hint': return choose('Puedes volver a intentarlo.', 'You can try again.')
    default: return String(key || '')
    }
  }

  function operationStage(stage) {
    switch (String(stage || '')) {
    case 'auth.submitting_credentials': return choose('Enviando credenciales…', 'Submitting credentials…')
    case 'auth.verifying_credentials': return choose('Verificando credenciales…', 'Verifying credentials…')
    case 'auth.waiting_for_sso': return choose('Completa el inicio de sesión de tu organización en la ventana segura…', 'Complete your organization sign-in in the secure window…')
    case 'auth.completing_sso': return choose('Completando inicio de sesión SSO…', 'Completing SSO sign-in…')
    case 'auth.waiting_for_human_verification': return choose('Completa la verificación humana en la ventana segura…', 'Complete human verification in the secure window…')
    case 'auth.completing_human_verification': return choose('Completando verificación humana…', 'Completing human verification…')
    case 'auth.waiting_for_two_factor': return choose('Esperando el código de dos pasos', 'Waiting for two-factor code')
    case 'auth.submitting_two_factor': return choose('Enviando código de dos pasos…', 'Submitting two-factor code…')
    case 'auth.verifying_two_factor': return choose('Verificando código de dos pasos…', 'Verifying two-factor code…')
    case 'auth.scanning_security_keys': return choose('Buscando llaves de seguridad…', 'Scanning for security keys…')
    case 'auth.select_security_key': return choose('Toca la llave que quieres usar…', 'Touch the security key you want to use…')
    case 'auth.touch_security_key': return choose('Toca tu llave de seguridad…', 'Touch your security key…')
    case 'auth.security_key_pin_required': return choose('Tu llave necesita un PIN.', 'Your security key needs a PIN.')
    case 'auth.submitting_security_key_pin': return choose('Enviando PIN a la llave…', 'Submitting the security key PIN…')
    case 'auth.security_key_pin_failed': return choose('El PIN no fue aceptado; inténtalo otra vez.', 'The PIN was not accepted; try again.')
    case 'auth.verifying_security_key_user': return choose('Verificando tu presencia…', 'Verifying user presence…')
    case 'auth.verifying_security_key': return choose('Verificando la llave de seguridad…', 'Verifying security key…')
    case 'auth.cancelling_security_key': return choose('Cancelando autenticación con llave…', 'Cancelling security-key authentication…')
    case 'auth.finalizing': return choose('Finalizando inicio de sesión…', 'Finalizing sign-in…')
    case 'auth.loading_account': return choose('Cargando tu cuenta…', 'Loading your account…')
    case 'auth.signing_out': return choose('Cerrando sesión…', 'Signing out…')
    case 'auth.disconnecting': return choose('Desconectando antes de cerrar sesión…', 'Disconnecting before sign-out…')
    case 'auth.clearing_session': return choose('Eliminando la sesión compartida…', 'Clearing the shared session…')
    case 'tunnel.preparing_connection': return choose('Preparando la conexión…', 'Preparing connection…')
    case 'tunnel.selecting_server': return choose('Seleccionando servidor…', 'Selecting server…')
    case 'tunnel.connecting': return choose('Conectando…', 'Connecting…')
    case 'tunnel.securing_session': return choose('Verificando la sesión cifrada…', 'Verifying encrypted session…')
    case 'tunnel.cancelling': return choose('Cancelando conexión…', 'Cancelling connection…')
    case 'tunnel.disconnecting': return choose('Desconectando…', 'Disconnecting…')
    case 'settings.applying_feature': return choose('Aplicando protección…', 'Applying protection setting…')
    case 'settings.applying_protocol': return choose('Aplicando protocolo…', 'Applying protocol…')
    case 'settings.applying_dns': return choose('Aplicando DNS…', 'Applying DNS…')
    case 'settings.applying_split_tunneling': return choose('Aplicando túnel dividido…', 'Applying split tunneling…')
    case 'support.submitting_report': return choose('Enviando reporte…', 'Submitting report…')
    case 'support.submitting_connection_feedback': return choose('Guardando opinión…', 'Recording feedback…')
    case 'support.feedback_recorded': return choose('Opinión guardada', 'Feedback recorded')
    case 'support.requesting_netshield_statistics': return choose('Actualizando estadísticas de NetShield…', 'Refreshing NetShield statistics…')
    case 'store.saving': return choose('Guardando…', 'Saving…')
    case 'request.submitting': return choose('Procesando…', 'Working…')
    default: return String(stage || '')
    }
  }

  function error(code, fallback) {
    switch (String(code || '')) {
    case 'operation_conflict': return choose('Hay otra operación incompatible en curso.', 'Another incompatible operation is running.')
    case 'two_factor_failed': return choose('El código no fue aceptado. Inténtalo de nuevo.', 'The code was not accepted. Try again.')
    case 'login_failed': return choose('Las credenciales no fueron aceptadas.', 'The credentials were not accepted.')
    case 'api_unreachable': return choose('No se pudo alcanzar la API de Proton. Revisa la red e inténtalo de nuevo.', 'Could not reach the Proton API. Check the network and try again.')
    case 'api_response_invalid': return choose('La respuesta de red de Proton no fue válida. Inténtalo de nuevo.', 'Proton returned an invalid network response. Try again.')
    case 'api_rate_limited': return choose('Proton recibió demasiados intentos. Espera un momento e inténtalo de nuevo.', 'Proton received too many attempts. Wait a moment and try again.')
    case 'api_server_error': return choose('La API de Proton no está disponible temporalmente.', 'The Proton API is temporarily unavailable.')
    case 'tls_pin_mismatch':
    case 'tls_pinning_unavailable':
    case 'tls_certificate_invalid': return choose('No se pudo verificar de forma segura la API de Proton.', 'The Proton API could not be verified securely.')
    case 'srp_verification_failed':
    case 'srp_server_proof_invalid': return choose('No se pudo verificar de forma segura el inicio de sesión.', 'The sign-in exchange could not be verified securely.')
    case 'two_factor_session_expired': return choose('La sesión venció. Inicia sesión de nuevo.', 'The session expired. Sign in again.')
    case 'human_verification_required': return choose('No se pudo completar la verificación humana de Proton.', 'Proton human verification could not be completed.')
    case 'human_verification_in_progress': return choose('Ya hay una verificación humana en curso.', 'Human verification is already in progress.')
    case 'sso_required': return choose('No se pudo completar el inicio de sesión SSO de tu organización.', 'Your organization SSO sign-in could not be completed.')
    case 'fido2_key_not_found': return choose('No se encontró una llave de seguridad.', 'No security key was found.')
    case 'fido2_pin_invalid': return choose('El PIN de la llave no es correcto.', 'The security key PIN is incorrect.')
    case 'fido2_pin_not_set': return choose('La llave necesita tener un PIN configurado.', 'The security key must have a PIN configured.')
    case 'fido2_timeout': return choose('La llave no respondió a tiempo.', 'The security key timed out.')
    case 'fido2_key_invalid': return choose('Esta llave no puede autenticar la cuenta.', 'This key cannot authenticate the account.')
    case 'fido2_not_supported': return choose('Este sistema no tiene soporte disponible para llaves de seguridad.', 'Security-key support is unavailable on this system.')
    case 'fido2_already_active': return choose('Ya hay una autenticación con llave en curso.', 'Security-key authentication is already in progress.')
    case 'fido2_not_active': return choose('La autenticación con llave ya no está activa.', 'Security-key authentication is no longer active.')
    case 'fido2_pin_already_submitted': return choose('El PIN de la llave ya fue enviado.', 'The security-key PIN was already submitted.')
    case 'fido2_pin_not_requested': return choose('La llave no está solicitando un PIN.', 'The security key is not requesting a PIN.')
    case 'fido2_cancelled': return choose('Se canceló la autenticación con llave.', 'Security-key authentication was cancelled.')
    case 'fido2_failed': return choose('No se pudo autenticar con la llave.', 'Security-key authentication failed.')
    case 'agent_disconnected': return choose('Se perdió la conexión con el agente. Reconectando…', 'Agent connection was lost. Reconnecting…')
    case 'agent_socket_error': return choose('No se pudo contactar al agente. Reintentando…', 'Could not reach the agent. Retrying…')
    case 'backend_not_ready':
    case 'backend_unavailable':
    case 'bridge_unavailable':
    case 'bridge_io':
    case 'core_unavailable': return choose('El backend oficial de Proton no está disponible.', 'The official Proton backend is unavailable.')
    case 'connection_failed': return choose('No se pudo completar la conexión VPN.', 'The VPN connection could not be completed.')
    case 'local_agent_failed': return choose('Proton rechazó la configuración de esta conexión.', 'Proton rejected this connection configuration.')
    case 'local_agent_timeout': return choose('Proton no confirmó la sesión VPN a tiempo.', 'Proton did not confirm the VPN session in time.')
    case 'local_agent_disconnected': return choose('Se perdió el canal de control cifrado de Proton.', 'Proton’s encrypted control channel was lost.')
    case 'p2p_not_allowed': return choose('Se detectó tráfico P2P. Este servidor no permite P2P para tu plan; usa un servidor P2P.', 'P2P traffic was detected. This server does not allow P2P for your plan; use a P2P server.')
    case 'local_agent_jailed': return choose('Proton restringió esta sesión VPN.', 'Proton restricted this VPN session.')
    case 'maximum_sessions_reached': return choose('Tu cuenta alcanzó el máximo de conexiones VPN simultáneas.', 'Your account reached its simultaneous VPN connection limit.')
    case 'vpn_certificate_expired': return choose('El certificado VPN venció; vuelve a iniciar sesión.', 'The VPN certificate expired; sign in again.')
    case 'connection_not_owned': return choose('Reconecta con este cliente para cambiar funciones de la conexión activa.', 'Reconnect with this client to change live connection features.')
    case 'connection_active': return choose('Desconecta la VPN antes de cambiar esta opción.', 'Disconnect the VPN before changing this setting.')
    case 'reconnect_required': return choose('Reconecta la VPN para aplicar esta opción.', 'Reconnect the VPN to apply this setting.')
    case 'connector_gate_violation': return choose('La operación no pudo obtener de forma segura el conector VPN.', 'The operation could not safely obtain the VPN connector.')
    case 'feature_restricted': return choose('Esta función no está incluida en tu plan.', 'This feature is not included in your plan.')
    case 'feature_unavailable': return choose('Esta función no está disponible con el backend actual.', 'This feature is unavailable with the current backend.')
    case 'protocol_unavailable': return choose('Ese protocolo no está disponible en los backends instalados.', 'That protocol is unavailable in the installed backends.')
    case 'setting_conflict':
    case 'profile_settings_conflict': return choose('Esta configuración entra en conflicto con otra opción activa.', 'This setting conflicts with another active option.')
    case 'split_tunneling_unavailable': return choose('El túnel dividido no está disponible en este sistema.', 'Split tunneling is unavailable on this system.')
    case 'split_tunneling_kill_switch_conflict': return choose('Desactiva Kill Switch antes de activar el túnel dividido.', 'Turn off Kill Switch before enabling split tunneling.')
    case 'split_tunneling_empty_selection': return choose('Selecciona al menos una aplicación o rango IP antes de activar este modo.', 'Select at least one application or IP range before enabling this mode.')
    case 'server_not_found': return choose('No se encontró un servidor disponible para ese destino.', 'No available server was found for that target.')
    case 'server_feature_mismatch': return choose('El servidor seleccionado no admite la función solicitada.', 'The selected server does not support the requested feature.')
    case 'server_gateway_mismatch': return choose('El servidor seleccionado no pertenece a ese Gateway.', 'The selected server does not belong to that Gateway.')
    case 'report_issue_submit_failed': return choose('No se pudo enviar el reporte.', 'The report could not be sent.')
    case 'store_io': return choose('No se pudo guardar la configuración local.', 'Could not save local settings.')
    case 'profile_limit_reached': return choose('Se alcanzó el límite de perfiles.', 'The profile limit has been reached.')
    case 'profile_not_found': return choose('Ya no existe ese perfil.', 'That profile no longer exists.')
    case 'recent_not_found': return choose('Ya no existe esa conexión reciente.', 'That recent connection no longer exists.')
    case 'invalid_default_connection': return choose('La conexión predeterminada ya no es válida.', 'The default connection is no longer valid.')
    case 'invalid_profile_target':
    case 'invalid_recent_target': return choose('El destino guardado ya no es válido.', 'The saved target is no longer valid.')
    case 'invalid_dns': return choose('Revisa las direcciones de DNS.', 'Check the DNS addresses.')
    case 'invalid_split_apps': return choose('La lista de aplicaciones contiene una entrada inválida.', 'The application list contains an invalid entry.')
    case 'invalid_split_ips': return choose('La lista contiene un rango IP inválido.', 'The list contains an invalid IP range.')
    case 'invalid_params': return choose('La solicitud contiene datos inválidos.', 'The request contains invalid data.')
    case 'invalid_external_url':
    case 'untrusted_external_url': return choose('Se rechazó un enlace externo no válido o no confiable.', 'An invalid or untrusted external link was refused.')
    case 'frame_too_large': return choose('La solicitud local excede el tamaño permitido.', 'The local request exceeds the allowed size.')
    case 'operation_not_active': return choose('La operación que intentabas controlar ya terminó.', 'The operation you tried to control has already finished.')
    case 'too_many_pending_requests': return choose('Hay demasiadas solicitudes locales en curso.', 'Too many local requests are in progress.')
    case 'method_not_found':
    case 'invalid_method': return choose('La versión instalada no admite esta operación.', 'The installed version does not support this operation.')
    case 'invalid_locale': return choose('Selecciona español o inglés.', 'Select Spanish or English.')
    case 'not_authenticated': return choose('Inicia sesión para continuar.', 'Sign in to continue.')
    default: return choose('No se pudo completar la operación.', 'The operation could not be completed.')
    }
  }
}
